### PR TITLE
Added support Node 12.x.x & 13.x.x. Updated deprecated functions for v8.

### PR DESCRIPTION
**Pull request by oktapodia**

### CODE REVIEW

**Comment by dsteinman** [comment]
I can confirm this branch works on MacOS with Node v12.8.1, thanks!

**Comment by rwwagner90** [comment]
Could we get a new release that includes this please?

**Comment by oktapodia** [comment]
Will do as soon as possible

**Comment by dsteinman** [comment]
> Could we get a new release that includes this please?

Until the release is made you can change your package.json to point to the master branch:

```
"dependencies": {
    "robotjs": "git+https://github.com/octalmage/robotjs.git#master"
```

**Comment by rwwagner90** [comment]
@dsteinman yeah, I have done that. I just prefer to use a released version.

**Comment by jorgecuevas92** [comment]
Works on Ubuntu 18.04 and Node v12.13.1

**Pull request merged**
