### PR TITLE
Actually send scancodes after figuring them out

### PR DESCRIPTION
**Pull request by PureSpider**
If we do all this work to figure out associated scancodes for virtual keys, we should use them to actually send keystrokes as such.

### CODE REVIEW

**Comment by oktapodia** [comment]
Thank you for your PR @PureSpider  and sorry for the delay, I am struggling to understand exactly what this PR is doing, can you please explain?

**Comment by PureSpider** [comment]
Sure:
* for the method to actually send scan codes, the `KEYEVENTF_SCANCODE` flag needs to be set. If it is not, the virtual keys method and the associated value is used instead, while the scan code value is ignored 
* modifiers and keys should be pressed and released in a more natural way: modifier press, then key press, then key release, then modifier release
* the time between modifier press and key press should never be zero - some applications struggle to recognize the events correctly if it is. Same goes for key release.

Let me know if you have further questions

**Comment by oktapodia** [comment]
Sounds amazing! Thank you! I'll merge it after Appveyor finish its work

**Comment by oktapodia** [comment]
Thank you for your PR!

**Pull request merged**
