### PR TITLE
Support additional keys (capslock, numpad-keys, right alt+control).

### LINKED ISSUE #355: Support clicks with key modifiers
It would be helpful if the mouseClick() method could accept key modifiers.
For example, Ctrl+Shift+Click could be served with one request.

### LINKED ISSUE #358: Support additional keys
It would be useful to add support for the rest keys:
 * capslock
 * numpad-keys (num-lock, +, _, *, +)
 * right alt
 * right control

### PR DESCRIPTION
**Pull request by MariaDima**
Closes #358

### CODE REVIEW

**Comment by MariaDima** [comment]
It also includes https://github.com/octalmage/robotjs/pull/261.
If accepted, please merge that patchset first.

**Comment by octalmage** [comment]
Sorry everyone, releasing and building is currently difficult since I have to spin up a bunch of VMs. I'm going to work on getting TravisCI publishing so it's easier to test and deploy. Thanks for the PR!

**Comment by Chinafreak** [comment]
any plan for this merge?

**Comment by oktapodia** [comment]
Thank you for your PR @MariaDima  and sorry for the delay, can you please add some tests before getting this one merged?

**Pull request merged**
