### PR TITLE
Fixed Linux Y-axis scrolling bug

### LINKED ISSUE #301: Linux Y-axis scrolling bug
[this](https://github.com/octalmage/robotjs/search?utf8=%E2%9C%93&q=YTest&type=) should be `XTest`

### PR DESCRIPTION
**Pull request by dimatter**
Resolves #301

### CODE REVIEW

**Comment by scottrippey** [comment]
I too am having this issue, but I tested these changes and it works!  How about we get this merged?

**Comment by octalmage** [comment]
I'll take a look this weekend, thanks for the PR!

**Comment by manojsinghnegiwd** [comment]
@octalmage Is this resolved?

**Comment by octalmage** [comment]
Sorry everyone, releasing and building is currently difficult since I have to spin up a bunch of VMs. I'm going to work on getting TravisCI publishing so it's easier to test and deploy. Thanks for the PR!

**Pull request merged**
