### PR TITLE
Support Unicode Characters for .typeString()

### LINKED ISSUE #16: Printing UTF-8 Characters with accents
Hi,

when you try to typeString a character with accents, the returned string is not correct.

For example, when I try `robot.typeString('à')` it returns `ￃﾠ`.

The same happens when I try to print an `ñ`, it returns `ￃﾱ`.

Is there a way to make this work?

### PR DESCRIPTION
**Pull request by zz85**
Here's is preliminary patch for support unicode characters in robotjs for `.typeString()`.

```js
robot.typeString('Àçćéñtéd'); // works
robot.typeString('你好吗？'); // works
robot.typeString('😆💩🌺😍👍😠🐠😝😢🤣😢🦑'); // works
```

This fixes #16 #30

It has does simple UTF-8 parsing (without validation) and I have tested this with Chinese and accented characters [edit: and emjios] on MacOS.

~~However, I have not figured how to have emojis sending yet nor have I have tested it on other platforms although I've tried to make the code changes minimal here.~~

### CODE REVIEW

**Comment by zz85** [comment]
After some amount of trial and error, it seems `CGEventKeyboardSetUnicodeString` expects a UTF-16 character instead, will be update this PR once I get it working...

**Comment by zz85** [comment]
Update: After decoding, characters are re-encoded into UTF-16 to be used with CGEventKeyboardSetUnicodeString. This fixes all sending codepoints higher than 0x10000. That means emojis now work :)

**Comment by octalmage** [comment]
This is amazing, thank you so much for looking into this. I'll check it out soon!

**Comment by zz85** [comment]
Yay, I think this is the smallest set of changes to get unicode working but I'm pretty sure there's a better way to structure this. Let me know if you've a way to make it better :)

**Comment by alefefen** [comment]
Is it possibile to create a new release for that, there is need in a project and i think more people want to have this support

**Comment by zz85** [comment]
@octalmage would it be fine to merge this first?

**Comment by alefefen** [comment]
of course ... do you know when this will be done?

**Comment by lmmfranco** [comment]
@octalmage What about merging this PR? Seems a nice addition.

**Comment by alefefen** [comment]
I do not have a problem if you merge this pr with #326

**Comment by profbiss** [comment]
This does not work in Windows

**Comment by yalexx** [comment]
Hello guys, how can i run this branch locally. I know its noob question but do i have only to pull it or this keypress.c must be compiled. And what is the git command to pull this specific branch.

**Comment by HarrySarson** [comment]
See https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally.

Which boils down to running the following from your shell from within a clone of the robotjs repository.

```bash
git fetch origin pull/276/head:unicode
git checkout unicode
```

**Comment by octalmage** [comment]
Sorry everyone! I've been busy, but thanks again! I'll get a new release out this weekend.

**Comment by alice0meta** [comment]
Excited about that upcoming new release :)

**Comment by alice0meta** [comment]
I don't know the best way to do this, but I grabbed HEAD and put it in a release so that I could use this library. https://www.npmjs.com/package/robotjs_head_2017-12-01

**Comment by lmmfranco** [comment]
@alice0meta you can use a fork directly as mom dependency. https://docs.npmjs.com/cli/install

**Comment by georgehdd** [comment]
@octalmage - any chance you will be releasing an official fix soon?

**Comment by samantrader** [comment]
@zz85   hi    how can use your change that support utf in windows version

**Pull request merged**
