### PR TITLE
Throw error if mouse coordinates are out of bounds.

### LINKED ISSUE #68: Throw error if mouse event is out of bounds.

### PR DESCRIPTION
**Pull request by octalmage**
Just adding additional error handling. 

Could someone confirm this works in a multi-monitor setup? 

cc: @danyshaanan @ryanramage @Deltatiger.

Thanks! 

Closes #68.

### CODE REVIEW

**Comment by octalmage** [comment]
I was finally able to test this and it breaks multi-monitor support. I'm going to look into it when I have time.

**Comment by Deltatiger** [comment]
Sorry was not able to check due to lack of time. Will check it out and see what I can do about this today.

**Comment by octalmage** [comment]
No worries! I was able to use my iPad as a second monitor, it works great! I also found a few other multi-screen related bugs so it was good I got to test it.

**Comment by octalmage** [comment]
Closing this until we get multi-monitor support.

**Pull request closed without merging**
