### PR TITLE
Unicode tap

### LINKED ISSUE #351: Support typing of Unicode Characters for Win/Mac (similar to keyTap)
It would be helpful if unicode characters were supported for the keyTap method (windows & MAC).
Windows support for typeString() is also an asset.

### PR DESCRIPTION
**Pull request by MariaDima**
Tested on Windows and Mac.

* Added a new unicodeTap() method.
* Supported Unicode characters for typeString() as well.
* Aligned the functionality of typeString() and typeStringDelayed() methods.
* Unit tests are added.

Additional comments can be found on the separate commits of this request.

Closes #351, #353, #386, #502

### CODE REVIEW

**Comment by octalmage** [comment]
Thank you! this looks great. I'll try to get it merged this week.

**Comment by octalmage** [comment]
Sorry everyone, releasing and building is currently difficult since I have to spin up a bunch of VMs. I'm going to work on getting TravisCI publishing so it's easier to test and deploy. Thanks for the PR!

**Comment by octalmage** [comment]
Again this is awesome, should there be a keyTap and a unicodeTap function?

**Comment by MariaDima** [comment]
I added a separate method for "tapping" for backwards compatibility reasons (not break existing applications if they use the new robotjs version).
I'm not sure if people want to migrate to unicodeTap.
If there is no need to keep backwards compatibility the unicodeTap is a superset of keyTap.

**Comment by Chinafreak** [comment]
Look interesting! How about unicodeToggle() like from keyToggle()? =)

**Comment by MariaDima** [comment]
The idea is to support unicode in general. That's why I generalized the solution to make all methods utilize the same business logic. Both key and string tapping can be consistent. As mentioned, I didn't modify the existing keyTap method for backwards compatibility issues. If we could find a more proper method name, I can change it before merge!

For toggling I think that this functionality is not possible. Toggling refers to key down/key up, while in our case we would like to type a character exactly as it is. Toggle is important for key combinations, but I think that this makes sense only when you run a program on your machine or on another machine that has the same locale. For example, remote commands are not covered by toggle. A unicode string on the other hand is life saving!

**Comment by Chinafreak** [comment]
This is the reason which I wanted to have toggling per unicode since I would love to use combination with special chars from my german keyboards which it's not working currently. I'm pretty sure there is a way. 
I've already tried but I'm not C++ experts. However I'll do some research and I hope I can find anything.

**Comment by Chinafreak** [comment]
I got unicodeToggle working in Windows (not sure about Mac) from your code. Is there any way to pull request on your robotjs repo?

**Comment by MariaDima** [comment]
What problem do you have with German Characters?
I was also working with German & Greek keyboards. I didn't face any problem, so I think that you would be ok if you use this PR.

You can either use my cloned repo (https://github.com/MariaDima/robotjs/tree/0.4.8_beta) until @octalmage checks my PR, or make a clone of your own and cherry-pick my commits from the cloned repo corresponding branch (https://github.com/MariaDima/robotjs/commits/UnicodeTap).

**Comment by SpencerCDixon** [comment]
@octalmage any word on this getting merged in?

**Comment by codealchemist** [comment]
This is really useful guys! Awesome work!
Hope we can have it merged sometime.
Thanks!

**Comment by eboukamza** [comment]
@MariaDima I have tested your code in Linux and `typeString()` do not work. also unit test always passing even when I change expected value.

**Comment by octalmage** [comment]
I'll look at Linux support to get this merged. I agree it's important, just haven't had much free time yet this year.

**Comment by oktapodia** [comment]
Thank you for your PR @MariaDima and sorry for the delay, can you please resolve the conflicts?

**Comment by Th3S4mur41** [comment]
@MariaDima is no longer working on the project and I have no access to her private fork.
I've create a new pull request to fix the merge conflict: https://github.com/octalmage/robotjs/pull/527
Could you please check this one instead

**Pull request merged**
