### PR TITLE
Windows scroll

### PR DESCRIPTION
**Pull request by Deltatiger**
Added the windows part of the mouse scroll. Tested the basics and it works. The Mac and Linux parts need to be added and tested.

Check the feature and tell me if any changes are to be made.

### CODE REVIEW

**Comment by octalmage** [comment]
Fantastic thanks! I'll try to take a look tonight.

**Comment by Deltatiger** [comment]
Should I also create a function for scrollMouseSmooth ? Just like the one for moveMouseSmooth ?

**Comment by octalmage** [comment]
eh not yet. I'm going to work on this now.

**Comment by octalmage** [comment]
Got Mac support in ded851cd5e4b1ffc23fb75b8e9977986ab91d9a1, I guess you should merge this into your fork?

**Comment by octalmage** [comment]
Also could we use this syntax: 

```
robot.scrollMouse(20, "up");
robot.scrollMouse(20, "down");
```

**Comment by Deltatiger** [comment]
Ok I will change it to the new format and then send a PR. Everything could be merged after that.

**Comment by octalmage** [comment]
Fantastic thanks a ton! Would you be interested in being the official Windows maintainer? I'm not sure what that means, but you'd at least be an official collaborator.

**Comment by octalmage** [comment]
Got scrollMouse implemented for Linux! Updated my branch. 

MMMouseWheelDirection is the same for all OSes, should we move it outside the conditionals?

**Comment by Deltatiger** [comment]
Yes the MMMouseWheelDirection can be moved out of the conditionals. I think this should be done once that part is done. You can merge it with your main stream.

**Comment by octalmage** [comment]
This code is actually giving me some issues on Windows XP: 

```
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
  robotjs.cc
s:\documents\apps\robotjs\src\os.h(26): warning C4005: 'STRICT' : macro redefin
ition [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
          C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\windef.h(16) :
  see previous definition of 'STRICT'
  deadbeef_rand.c
  mouse.c
..\src\mouse.c(220): error C2275: 'INPUT' : illegal use of this type as an expr
ession [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
          C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\winuser.h(5341)
   : see declaration of 'INPUT'
..\src\mouse.c(220): error C2146: syntax error : missing ';' before identifier
'mouseScrollInput' [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(220): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(221): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(221): error C2224: left of '.type' must have struct/union type [
S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(222): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(222): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(223): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(223): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(224): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(224): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(225): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(225): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(226): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(226): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(227): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(227): error C2224: left of '.mi' must have struct/union type [S:
\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(228): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(228): warning C4133: 'function' : incompatible types - from 'int
 *' to 'LPINPUT' [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(228): error C2065: 'mouseScrollInput' : undeclared identifier [S
:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(275): warning C4244: '+=' : conversion from 'double' to 'size_t'
, possible loss of data [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(276): warning C4244: '+=' : conversion from 'double' to 'size_t'
, possible loss of data [S:\Documents\Apps\robotjs\build\robotjs.vcxproj]
  keypress.c
  keycode.c
  screen.c
  screengrab.c
  snprintf.c
..\src\snprintf.c(943): warning C4018: '>' : signed/unsigned mismatch [S:\Docum
ents\Apps\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(960): warning C4018: '>' : signed/unsigned mismatch [S:\Docum
ents\Apps\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(969): warning C4018: '>' : signed/unsigned mismatch [S:\Docum
ents\Apps\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(981): warning C4018: '>' : signed/unsigned mismatch [S:\Docum
ents\Apps\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(992): warning C4018: '>' : signed/unsigned mismatch [S:\Docum
ents\Apps\robotjs\build\robotjs.vcxproj]
  MMBitmap.c
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Documents and Settings\Administrat
or\Application Data\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Documents and Settings\\Administrator\\Application
Data\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd S:\Documents\Apps\robotjs
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

I'm looking into it, but I thought I tested this code already. Did I break something @Deltatiger?

**Comment by Deltatiger** [comment]
@octalmage Is this still causing problems ? If so I will look into it,

**Comment by octalmage** [comment]
@Deltatiger yeah I wasn't able to figure it out. I feel like an include or library might be missing but I'm not really sure.

**Comment by Deltatiger** [comment]
@octalmage Will look into it tonight

**Comment by Deltatiger** [comment]
@octalmage I am not getting any errors in Windows 7. I am currently on your master branch. Is this only happening in Win XP or does it occur everywhere ?

**Comment by octalmage** [comment]
I've only tested in Windows XP, I'll look into it some more later. What version of Visual Studio are you using? 

—
Jason StallingsSent from my iPhone

**Comment by Deltatiger** [comment]
I am using Visual Studio 2013. Compiling via node-gyp build

**Comment by octalmage** [comment]
Hmm, I'm using Visual Studio 2008, I couldn't get 2013 on XP. I think I'm going to comment out the Windows code for now so I can release a new version, until I can figure out what's wrong.

**Comment by Deltatiger** [comment]
Ok I will also check it out on a VM

**Pull request merged**
