### PR TITLE
Workaround for games not detecting mouse moves.

### LINKED ISSUE #159: moveMouse / dragMouse in games
I ran into an other issue, that again might be OS specific. I am using a Potentiometer that is mapped to my screen width, which I would like to use as a controller for my game. But whenever the mouse input has to be used in a game, it doesn't detect the movement of the cursor.

Button presses works perfectly. And I tried with dragMouse too. 

Anyone got this to work?

### PR DESCRIPTION
**Pull request by octalmage**
Resolves #159.

### CODE REVIEW

**Comment by nroadley** [comment]
Hi Octalmage, 

I now tried the update, but still doesn't seem to work for me. Do I use the dragMouse function, or did you do it differently? 

Thanks for looking into this!

**Comment by octalmage** [comment]
I modified moveMouse and dragMouse, are neither of them working?

**Comment by octalmage** [comment]
It's probably related to https://github.com/octalmage/robotjs/issues/179

**Comment by nroadley** [comment]
I used dragMouse, can try with moveMouse tomorrow. Does it matter how you increment the mouse movement? In my case I am using a Slider to map the screen width to 0-100 steps, which I believe could be a problem if the cursor "jumps"?

And can confirm that Windows works without problem 👍

**Comment by octalmage** [comment]
@nroadley could we move this to #179!

**Pull request merged**
