### PR TITLE
Faster typing in Windows

### PR DESCRIPTION
**Pull request by ricardopolo**
Currently it takes about 200ms per key press, with this PR about 15ms
Fixes https://github.com/octalmage/robotjs/issues/530
Fixes https://github.com/octalmage/robotjs/issues/547

### CODE REVIEW

**Comment by Kyusung4698** [comment]
Hi, i've created an PR #560 regarding this issue which also fixes those issues for X11 (Linux).

**Comment by ricardopolo** [comment]
Would be awesome if #560 is merged!

**Comment by oktapodia** [comment]
Thank you for your PR.

@ricardopolo can you please resolve the conflicts? I'll merge straight after it.

**Comment by ricardopolo** [comment]
Dont need to merge. Part of https://github.com/octalmage/robotjs/pull/560/files

**Pull request closed without merging**
