### PR TITLE
Fixed the API link

### PR DESCRIPTION
**Pull request by IonicaBizau**
...because it was wrong. :star2:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
:tada: :smile:

**Comment by IonicaBizau** [comment]
@octalmage Forgot to say thanks for the awesome module! :cake:

**Comment by octalmage** [comment]
@IonicaBizau and I forgot to say thanks for the pull request!

**Comment by IonicaBizau** [comment]
:joy: :grin:

**Comment by octalmage** [comment]
:p

**Pull request merged**
