### PR TITLE
Fix mouseToggle

### PR DESCRIPTION
**Pull request by Zeukkari**
The mouseToggle function has some simple syntax errors and doesn't work. Here's a fix produced with minimal knowledge on C/C++ .

### CODE REVIEW

**Comment by petre2dor** [comment]
+1

**Comment by octalmage** [comment]
Awesome thanks! I was seriously about to do this. Same thing happened in e8da392dd8862f2a90b5bf7c30bf5365618e8b80 and 291890c90c7df423e10dde9e4c76cf601ce7ac97.

Would you mind changing it to use `Nan::Utf8String` like e8da392dd8862f2a90b5bf7c30bf5365618e8b80?

**Comment by Zeukkari** [comment]
like that?

**Comment by octalmage** [comment]
Perfect! Thanks again!

**Pull request merged**
