### PR TITLE
add projecttalk link

### PR DESCRIPTION
**Pull request by manukall**
adds a link to the robotjs messageboard on projecttalk.io.

i find it quite nice to have the possibility of asynchronous communication next to gitter, so not everybody has to be online at the same time.

### CODE REVIEW

**Comment by octalmage** [comment]
This is what issues are for! I'll consider it though.

**Comment by manukall** [comment]
i agree in a way. many projects see issues more as a bug tracker though and have separate message boards for usage questions or other things that aren't bugs.
thanks for checking out the project and for considering the pull request. please also let me know if you have any other feedback.

**Comment by octalmage** [comment]
I've never heard of projecttalk and it looks interesting.

**Comment by manukall** [comment]
thanks :smile: 
that's because it only just started.

**Comment by octalmage** [comment]
Nice! I'm a fan already, but personally I like to use issues for any kind of discussion. This could become an issue as the project gains popularity so I'm going to keep this open for now. 

Hopefully others will chime in!

**Comment by octalmage** [comment]
Decided against it, I like using the issues for this! 

Thanks!

**Pull request closed without merging**
