### PR TITLE
Migrate to SendInput from mouse_event

### PR DESCRIPTION
**Pull request by Deltatiger**
Moving from mouse_event to SendInput using Absolute mouse positioning.

### CODE REVIEW

**Comment by Deltatiger** [comment]
This seems to be causing some failure. Will check it out.

**Comment by octalmage** [comment]
I think it was just an environment failure, I'll restart it.

**Comment by octalmage** [comment]
Tests passed! I'll test this soon, probably this weekend. Thanks a ton!

**Comment by octalmage** [comment]
Looks and works good! Thank you so much for handling this.

**Pull request merged**
