### PR TITLE
Multi monitor support for mouseMove and dragMouse

### LINKED ISSUE #88: [multi-monitor] moveMouse wont move to negative position on mac
Hey... I use getMousePos to get the mouse position, and it returns negative values sometimes (multiple monitors above my laptop monitor).

I then try and use robot.moveMouse(800, -954) for example, and it only moves to 800, 0.

### PR DESCRIPTION
**Pull request by hristoterezov**
If the user has more than 1 monitor the coordinates of a monitor can be negative. Before the PR all the parameters for mouseMove and dragMouse were using size_t which is unsigned. That's why it was not possible to pass negative coordinates and move the mouse to a monitor with negative coordinates.

Fix #88

### CODE REVIEW

**Comment by octalmage** [comment]
This is awesome! Thank you! I'll take a look this weekend.

**Comment by jareddgotte** [comment]
@hristoterezov Nice! Have you made any updates since this PR? I'm interested in getting [getPixelColor()](http://robotjs.io/docs/syntax#getpixelcolorx-y) working across multiple monitors, too. It looks like the bitmap_find.c/h, color_find.c/h, MMPointArray.c/h, and screen.c/h files all use `MMPoint`, as well.

**Comment by octalmage** [comment]
Sorry everyone, releasing and building is currently difficult since I have to spin up a bunch of VMs. I'm going to work on getting TravisCI publishing so it's easier to test and deploy. Thanks for the PR!

**Comment by Chinafreak** [comment]
But I think negative mouse position is actually normal. It depends where your primary monitor is. If your primary monitor is in middle between two monitors from left and right, then the mouse position on this primary monitor starts at 0x 0y from top left which this make more sense. So it's already fine.

However, it would be good if this can be changed per settings. Such like:

```
var robot = require("robotjs");
robot.removeNegativeMouse(true);
```

or something like this. The main reason is that many applications works already pretty fine with negative mouse and changing the mouse position logic will just cause more problems.

**Comment by hristoterezov** [comment]
@jareddgotte Sorry for the delayed response! I haven't made any other changes after the PR and also nothing related to the getPixelColor.

**Comment by hristoterezov** [comment]
@Chinafreak I'm a little confused from your comment and here is why:
1. If you pass negative coordinates to `mouseMove` and `dragMouse` on the code before my change, it won't work properly. The purpose of my PR is to fix this.
2. I don't understand why would you need `removeNegativeMousePosition(true);`. I don't think that the code without my fix will work "pretty fine" with negative mouse position. Actually I think it won't work! But after my changes it is supposed to work with negative mouse position!
3. "changing the mouse position logic will just cause more problems" - The consumers of the library won't need to change anything. Basically before the PR the multi monitor use case was not working and after the PR it will start working.
4. I don't think `getPixelColor()` is related to my PR.

Could you please explain what you mean with your comment? Am I missing something?

**Comment by Chinafreak** [comment]
@hristoterezov 

Hey sorry, I just read your issue again and I think I misunderstood it. I think I  thought you wanted to remove negative mouse position. I'm not even sure if I wrote this on wrong issue, because it was so long time ago.

**Comment by mnakkara** [comment]
@hristoterezov @octalmage Any updates on this? I see this is in PR for over a year. It would be awesome if we can get this in a new release soon.

**Comment by johndatserakis** [comment]
@octalmage any word on this pr - looks like myself and a few others have been waiting for it for coming up on 2 years now - support for multiple monitors would be great, and @hristoterezov mentioned that the fix doesn't really effect other part of the code. Any status?

**Comment by saghul** [comment]
@octalmage Hey there! Is there anything we can do to help this one land? Not needing to rely on a fork would be ideal for us (Jitsi).

**Comment by oktapodia** [comment]
Thank you for your PR!

**Comment by saghul** [comment]
Thanks a lot @oktapodia! Any rough estimation on when this could make it into a release?

**Pull request merged**
