### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by DamonOehlman**
This is a quick PR to get to a base point for CI for testing robotjs.  Feel free to leave it open while I start to add more tests or bring it in now to allow yourself and others to start building tests also :)

### CODE REVIEW

**Comment by octalmage** [comment]
Fantastic! I wonder if we need to sleep after starting xvfb, I had issues with this in another project. 

I was also wondering if we should use an external program to confirm the mouse position? Might be overboard. We can add it later if necessary.

**Comment by octalmage** [comment]
Sorry, forgot to merge this!

**Comment by octalmage** [comment]
And the first tests passed! 

https://travis-ci.org/octalmage/robotjs/builds/57934287

Awesome work man!

**Comment by DamonOehlman** [comment]
No worries :) I'll definitely add more over time.

**Pull request merged**
