### PR TITLE
adding parameter to movemousesmooth function to allow users to set speed of movement

### LINKED ISSUE #174: Faster moveMouseSmooth
I've tried the [moveMouseSmooth](https://github.com/octalmage/robotjs/wiki/Syntax#movemousesmoothx-y) api, and it's quite awesome!
But it's a little bit slow to me, that while [remote controlling](https://github.com/maxogden/screencat), it takes more time to finish work.

So I think maybe it's possible for users to config the milliseconds to `wait`? maybe always 1 ms is okay?
Thanks! :sweat_smile: 

https://github.com/octalmage/robotjs/commit/38c17004c676307c1b2c318fe5a4c71115cbe78f#commitcomment-16814517

### PR DESCRIPTION
**Pull request by prithvihv**
Fix #174

### CODE REVIEW

**Comment by Boringboringstuff** [comment]
@octalmage Will you being merging this into the main repo?

**Comment by oktapodia** [comment]
Can you please fix the deprecations? @prithvihv

**Comment by QimatLuo** [comment]
if I use `1` it's very fast. If other than 1 will be very slow, no matter > 1 or < 1.
I'm running on Window 10 Node 12.

**Comment by john-ppd** [comment]
same, 1.5 or something around that speed would be nice, for now just seems to be either mega fast, or slow.

**Comment by b-marques** [comment]
Same here.

**Comment by boynet** [comment]
same here, but it was medium speed a few weeks ago (on windows 10)

**Comment by moritzruth** [comment]
We need an emoji for "same"

**Comment by moritzruth** [comment]
I use this as a workaround (TypeScript):

```typescript
import robot from "robotjs"

const INTERVAL = 1

export function moveMouseSmooth(x: number, y: number, duration: number): Promise<void> {
  return new Promise(resolve => {
    const startPos = robot.getMousePos()
    const delta = { x: x - startPos.x, y: y - startPos.y }

    const startTime = Date.now()

    const interval = setInterval(() => {
      const progress = (Date.now() - startTime) / duration

      if (progress > 1) {
        clearInterval(interval)
        resolve()
      } else {
        robot.moveMouse(startPos.x + (delta.x * progress), startPos.y + (delta.y * progress))
      }
    }, INTERVAL)
  })
}
```

**Pull request merged**
