### PR TITLE
Adding insert key. Fixes #184

### LINKED ISSUE #184: add the insert-Key for keyTap/Toggle
Hi, i would need the insert key.  
Im not too deep in all the c-stuff so im sorry if my question is a little dump. 
But as far as i understand, i would need to expand the key_names[]-array in robotjs.cc by some entry like: 
```
{ "insert", K_INSERT }
```
If so, i would do it and create a pull-request. If not, i would be really gratefull, if you would point out what to do, so that i could create the insert-key and others in the future.

### PR DESCRIPTION
**Pull request by chaosprinz**
Built and tested it under windows10. Cant test it on Mac/Linux

### CODE REVIEW

**Comment by chaosprinz** [comment]
Ok, see it. Got Problems under linux. Will fix it soon.

**Comment by octalmage** [comment]
I can help with the Mac and Linux side of things! Lets leave this open and just blocked!

**Comment by chaosprinz** [comment]
I think the last commit should fix it

**Comment by chaosprinz** [comment]
Looks fine, so far. :+1:

**Comment by Deltatiger** [comment]
@chaosprinz Could you please clean up the problem with removing tab spaces by your editor. It seems to have caused lot of changes.
It would be easy if you turned of that feature from your IDE / Editor.

**Comment by chaosprinz** [comment]
Oh, yeah. Will look into it.

**Comment by chaosprinz** [comment]
Was caused by the auto-fix of trailing Whitespace-"Feature" in Atom. Turned it of right now, copied back original files and reinserted my changes.
Sorry about that.

**Comment by octalmage** [comment]
No worries! Thanks a ton. This looks good.

**Pull request merged**
