### PR TITLE
Passing constant instead of zero for mouseButton on mouse move

### PR DESCRIPTION
**Pull request by noonat**
This is the fix described in #39.

### CODE REVIEW

**Comment by octalmage** [comment]
Thanks! Doesn't seem to be any regression, does this resolve an issue for you?

**Comment by noonat** [comment]
Hmm, I thought it did, but when I try to run the tests again now I'm not able to reproduce any issues with mouse move on master. I think I might have just moved the mouse accidentally while the tests were running the first time, haha.

**Comment by octalmage** [comment]
haha yeah, that happens. Hmm, well, this is technically right. I'll play around with it some.

**Comment by octalmage** [comment]
I'm going to merge this, since it works either way, and kCGMouseButtonLeft looks better than 0.

**Pull request merged**
