### PR TITLE
Fix for #347

### LINKED ISSUE #347: Waiting for event queue to be processed before returning from the methods
In my tests, it seems that keyboard typing methods returns immediately, w/o waiting the events queue to be processed by the system. That is - key type listeners are not activated yet, but the method already returns.

I've fixed this by adding arbitrary 50ms delay, but this is basically a race condition.

Any chance the methods can wait for events queue to be emptied?

### PR DESCRIPTION
**Pull request by SamuraiJack**
Resolves #347.

### CODE REVIEW

**Comment by octalmage** [comment]
Sorry everyone, releasing and building is currently difficult since I have to spin up a bunch of VMs. I'm going to work on getting TravisCI publishing so it's easier to test and deploy. Thanks for the PR!

**Comment by SamuraiJack** [comment]
Looking forward!

**Comment by eboukamza** [comment]
@SamuraiJack for X11, what is the difference if you use XSync() instead of XSynchronize()?

**Comment by 09211399028** [comment]
Hgdjkjgfdf

**Comment by 09211399028** [comment]
Jhygttuydxxc

**Pull request merged**
