### PR TITLE
Added special multimedia keycodes + restructured code

### LINKED ISSUE #91: [Question] Is there a way to press media keys like play/pause?
Most keyboards have them and, at least, Linux and Windows supports them by default.

### PR DESCRIPTION
**Pull request by vshymanskyy**
Restructured code a bit to make adding keyboard keycodes much easier.
Added multimedia keys + brightness control. This should be also possible on Cocoa but I didn't have a chance to investigate.
Fixes #91

### CODE REVIEW

**Comment by Zeukkari** [comment]
+1

**Comment by octalmage** [comment]
Thanks @vshymanskyy! I'll take a deeper look and test later today.

**Comment by petre2dor** [comment]
:+1:

**Comment by vshymanskyy** [comment]
I hope someone can test this on Windows & implement for OS X ;)

**Comment by octalmage** [comment]
That's my plan!

**Comment by vshymanskyy** [comment]
Are there any estimations when it could be published on the npm?
I want to publish a tutorial which uses multimedia keys ;)

**Comment by vshymanskyy** [comment]
Here is my story: https://www.facebook.com/vshymanskyy/posts/958231610900947?pnref=story

**Comment by octalmage** [comment]
Most likely before Thursday. I'm traveling today so I'll be pretty busy, but I'll try to take a look today.

**Comment by octalmage** [comment]
I'm getting errors compiling on Mac, working on fixing it now.

**Comment by vshymanskyy** [comment]
this should be simple to fix.. i just added it to every platform.

**Comment by octalmage** [comment]
I figured that out, but this change is causing a warning on Mac: 

```
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:329:11: warning: comparison of constant 'K_NOT_A_KEY' (-1) with expression of type 'MMKeyCode' (aka 'unsigned short') is always false [-Wtautological-constant-out-of-range-compare]
        if (*key == K_NOT_A_KEY) {
            ~~~~ ^  ~~~~~~~~~~~
```

I'm going to see if I can fix this real quick.

**Comment by vshymanskyy** [comment]
Please tell me if you need any help...

**Comment by octalmage** [comment]
I'm focusing my time on a breaking bug right now, if you can fix this warning please do.

**Comment by petre2dor** [comment]
any news about this? thanks :)

**Comment by octalmage** [comment]
I'm just going to merge it and fix the warning later, sorry for the delay.

**Comment by gurel** [comment]
Any ETA when this will be merged?

**Pull request merged**
