### PR TITLE
Enhancements to Keyboard Functions

### LINKED ISSUE #7: Add toggle function for keyboard.
Allow holding keys down, and releasing them.

### LINKED ISSUE #14: Possibly sleep after mouse/key events.
Apparently on some machines a delay is needed after a mouse move or click before the next action will work. This is probably an OS limitation. 

Since this is in C I can use usleep, I just need to find what the limitation is. 2 miliseconds works on Mac.

### PR DESCRIPTION
**Pull request by drquinn**
This PR makes a few enhancements to keyboard functionality.
- Exposes the KeyToggle function for use in Robotjs.
- Adds modifiers for KeyTap and KeyToggle.
- Adds the ability to write single characters to KeyTap and KeyToggle.
- Adds keys that were missing from KeyTap to both KeyTap and KeyToggle.
- Fixes a bug I noticed in KeyTap. Seems it was not releasing the key. I used the OSX keyboard viewer to see this. As already suggested in one of the issues, I added a sleep function to fix. I did not fix this in the mouse events, but the mssleep function can be reused.

Closes #7 
Closes #14

### CODE REVIEW

**Comment by octalmage** [comment]
Looks great, thanks a ton!! Let me test the changes then I'll merge it. 

:thumbsup:

**Comment by drquinn** [comment]
Awesome, no problem. Let me know if you want anything refactored or done differently. I plan to use and extend quite a bit of this library for controlling PCs with a data glove I'm working on.

**Comment by octalmage** [comment]
Wow sounds epic! Can't wait to see the project.

**Comment by octalmage** [comment]
@drquinn this is small, but could you add periods to the end of all errors? Thanks!

@maxogden does this PR line up with your projects needs?

**Comment by maxogden** [comment]
Sorry it's hard to tell from the diff (I am not very good at objective-c and don't have time to test out this branch at the moment), but my branch is here for reference https://github.com/maxogden/robotjs/commits/keyupdown

**Comment by octalmage** [comment]
No worries! I'll check it out. I just want to avoid any conflicts.

**Comment by octalmage** [comment]
I'm just going to merge and fix the style inconsistencies.

Thanks again!

**Comment by drquinn** [comment]
Sorry about the inconsistencies. Thanks for taking care of it!

**Pull request merged**
