### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by dthree**
BTW, Love it. Was thinking about this idea just a few weeks ago, and then I saw this. Great idea.

### CODE REVIEW

**Comment by octalmage** [comment]
Thanks for the PR and I'm glad you like the project! I'm having a hard time finding what was changed though, can you help me out?

**Comment by dthree** [comment]
You spelled "difficult" as "diffucult". That's all.

**Comment by octalmage** [comment]
Ah there it is! Thanks!!

**Comment by dthree** [comment]
No probs. And congrats on the this pjt's success!

**Comment by PowerWebsite** [comment]
I like it

**Pull request merged**
