### PR TITLE
v8::{Handle => Local} for node 12 compatibility

### LINKED ISSUE #458: node-gyp rebuild with electron node_headers does not work
## Expected Behavior
It should properly

## Current Behavior
The build fails

## Steps to Reproduce (for bugs)

1. Follow the steps to build electron [here](https://electronjs.org/docs/development/build-instructions-gn)
2. Then try `npm test`. This will go to `node_modules/robotjs` and do a `node-gyp rebuild`. This fails.

## Context
I can't get Electron's test environment to build properly. Please see [this electron issue](https://github.com/electron/electron/issues/16746) especially the debugging in [this comment](https://github.com/electron/electron/issues/16746#issuecomment-461077640)

Also, this is far outside my expertise. @nornagon suggested posting an issue here. Hopefully you can figure out what's going on becausue I can't. 

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: 10.15.0
* npm version: 6.4.1
* Operating System: macOS

### PR DESCRIPTION
**Pull request by nornagon**
fixes #458

### CODE REVIEW

**Comment by nornagon** [comment]
Ping on this? It's also needed for compatibility with Electron 5.

**Comment by octalmage** [comment]
Looks great thanks!

**Comment by ollar** [comment]
Is this fix already shipped to npm?

**Comment by emko** [comment]
is this on npm? or v12 still has issues?

**Comment by linonetwo** [comment]
Build from Github still failed.

**Pull request merged**
