### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jub3i**
spelling and link to linux install hints which i put in the wiki

### CODE REVIEW

**Comment by jub3i** [comment]
great project ... theres plenty which can accomplish this in linux world, but to be able to do it nodejs! much thanks :)

**Comment by octalmage** [comment]
Thanks! Glad you like the project! 

Could you leave out the wiki note? I'm not ready to advertise Linux support, it's got some issues.

**Comment by jub3i** [comment]
i can remove, but my suggestion is advertise! that hints woulda saved me some time if it was in the readme. the more info the better... let me know what you wanna do.

**Comment by octalmage** [comment]
See #19 and #17. The main issue is with getPixelColor, and I'm pretty sure the problem is this line:

    snprintf(hex, 7, "%06x", color);

I just haven't had time to look at it yet.

**Comment by octalmage** [comment]
I totally agree that more info is better. I'd just rather say Linux isn't supported until we get all the bugs worked out.

**Comment by octalmage** [comment]
I believe keyTap is also broken. I can take a look tomorrow if you don't get a chance. Should be easy to replace the snprintf line if that is the issue.

**Comment by jub3i** [comment]
jeez i shoulda checked the issues before i asked! :) if i do get a chance it'll be next weekend...

**Comment by octalmage** [comment]
Awesome, I appreciate everything! I have to do Linux dev in a VM, and it sucks.

**Comment by jub3i** [comment]
ok sure, ive got some plans using this lib, so im sure i'll get to it at some point. removed the wiki link.

**Comment by octalmage** [comment]
MERGE.

**Pull request merged**
