### PR TITLE
Fix error with mouse moving in Windows with multiple displays

### LINKED ISSUE #400: wrong mouse x , y
hi 
i use node 8 in windows 10
when i record mouse x , y it is not true
for example i click one point and get x , y with this  iohook
(  https://www.npmjs.com/package/iohook )
it say 
```
 x: 1552, y: 1077
```
but your code say
```
x:1242 y:862
```
i test with c# and c# say 
```
 x: 1552, y: 1077
```
why your package say something other?
image

### PR DESCRIPTION
**Pull request by vyatkin0**
RobotJS fails on Windows 10 environment with multiple displays when a primary display is not located on top left corner of entire virtual screen or displays have different resolutions and dpi scale factors.
It fixes #400

### CODE REVIEW

**Comment by Th3S4mur41** [comment]
Just tested the patch in our environment, but it didn't seem to bring improvements for our use case...

Environment was Windows 10 (1709) with dual screen.
As far as both screen have a DPI scaling of 100% everything is ok.
Even with a higher DPI scaling, there is still no issue as long as the activity is happening on the main screen.
However, there is a mouse offset as soon as the activity moves to a secondary screen when the main screen's DPI scaling is higher than 100%.
DPI scaling on the secondary screen might worsen the problem, but doesn't seem to be the most important setting at first

**Comment by vyatkin0** [comment]
Th3S4mur41, it looks like the patch was not installed correctly. Probably you have used previously compiled library from npm repository instead of updated version.

**Comment by Th3S4mur41** [comment]
vyatkin0 we actually made sure to properly recompile. We also tried to use your branch directly without success. Is there a way to verify that the patch is properly in place (maybe some traces)?

**Comment by Th3S4mur41** [comment]
@vyatkin0 did you have a chance to retest the patch?
We checked that we were properly calling the updateScreenMetrics(), but still no improvement.
Which Electron version did you use for your tests?

**Comment by vyatkin0** [comment]
@Th3S4mur41 I have retested the patch. It is OK.
RobotJS is not related to Electron.
I suppose you are developing remote control based on Elecron JS and Robot JS please see my pull request for jitsi-meet-electron-utils https://github.com/jitsi/jitsi-meet-electron-utils/pull/28 that solves the problem completely. Please notice also that you should to use Electron 3.0 beta because desktopCapturer in electron 2.0 doesn't work correctly in Windows 10.

**Comment by oktapodia** [comment]
Thank you for your PR and sorry for the delay, can you please resolve the conflicts?

**Comment by oktapodia** [comment]
Thank you for your PR!

**Pull request merged**
