### PR TITLE
Windows: Use SendInput instead of mouse_event for toggleMouse

### LINKED ISSUE #420: Windows: Use SendInput instead of mouse_event for toggleMouse
Based on Microsoft official documentation (https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-mouse_event), **mouse_event has been superseded**.

It would be good if we update to use the **SendInput** method for **toggleMouse** functionality.

### PR DESCRIPTION
**Pull request by MariaDima**
closes #420

### CODE REVIEW

**Comment by Deltatiger** [comment]
You should also cover MOUSEEVENTF_MIDDLEUP and MOUSEEVENTF_MIDDLEDOWN. Those are supported in the current API. I have submitted a PR which has both of those also.

**Comment by octalmage** [comment]
@Deltatiger is this a duplicate now?

**Comment by oktapodia** [comment]
Thank you for your PR @MariaDima  and sorry for the delay, can you please resolve the conflicts and add some tests?

**Comment by oktapodia** [comment]
You are right, looks like it has been added a while ago [there](https://github.com/octalmage/robotjs/commit/1c7b96a8bef620502e30bd13a04b1fd875c5da6c) Let me know if I'm wrong @Deltatiger @MariaDima

**Pull request closed without merging**
