### PR TITLE
Merge pull request #508 from gera2ld/fix/scrolling

### PR DESCRIPTION
**Pull request by gera2ld**
Fix bug introduced by #361 .
With this bug mouse scrolling does not work on Windows.

### CODE REVIEW

**Comment by oktapodia** [comment]
Thank you for your PR @gera2ld  and sorry for the delay, can you please add some tests?

**Comment by gera2ld** [comment]
There are already tests for this, maybe they didn't pass when the bug is introduced to master.

**Comment by aeroreyna** [comment]
This works to solve the issue for me.
Windows 10

**Comment by oktapodia** [comment]
Thank you for your PR

**Pull request merged**
