### PR TITLE
Reorganize readme

### PR DESCRIPTION
**Pull request by dthree**
Suggested re-org / improvements :smiley:

### CODE REVIEW

**Comment by dthree** [comment]
Err... the ## [API](blah) header got kind of botched, but I can't figure out how to re-edit it when I just did the changes on `github.com`. Maybe we can just quickly fix after merge, if everything else is OK.

**Comment by aequasi** [comment]
go to your fork, under the `patch-1` branch, and edit the file there

**Comment by dthree** [comment]
Thanks @aequasi. This is fixed.

**Comment by octalmage** [comment]
Looks good!  One question, why Getting Started instead of Examples? Examples seems more appropriate since it's not a guide. I think it would be nice to have a getting started section though.

**Comment by dthree** [comment]
Good point - fixed. :)

**Pull request merged**
